### ISSUE TITLE
[BUG] Failed to build the workspace with Tuist/ Xcode 14.3 

### ISSUE THREAD

**Issue by hassan-ioki** [stripe/stripe-ios#2446]
## Summary
I am unable to build the workspace with Tuist/ Xcode 14.3 

## iOS version
14+

## Installation method
I install with Tuist but it fails with error

## SDK version
23.6.0

## Other information
The error is: 
`Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -workspace /Users/muhammad/../Carthage/Checkouts/stripe-ios/Stripe.xcworkspace -scheme StripeCameraCoreTestUtils -configuration Release -derivedDataPath /Users/muhammad/Library/Caches/org.carthage.CarthageKit/DerivedData/14.3_14E222b/stripe-ios/23.6.0 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive VALIDATE_WORKSPACE=NO -archivePath /var/folders/xn/sqdyt50x5_d_0ffq6vjn_74c0000gn/T/stripe-ios SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/muhammad/../Tuist/Dependencies/Carthage/Checkouts/stripe-ios)
`

The build error is: 
`module 'StripeCameraCore' was not compiled for testing
@_spi(STP)@testable import StripeCameraCore
`

**Comment by davidme-stripe** [comment]
That's strange @hassan-ioki, thanks for filing this. It looks like something is picking up on and building the StripeCameraCoreTestUtils, which is unexpected. Can you share the Tuist command you're calling, and a snippet from your Tuist config to show how you're integrating Stripe?

**Comment by hassan-ioki** [comment]
We use Carthage through Tuist, 
`let carthage = CarthageDependencies([ 
.
.
.github(path: "stripe/stripe-ios", requirement: .exact("22.5.0")),
])`

So for discussion, I am on `22.5.0` but I checked with the latest and it fails there. So for us, our old version is working well. 
Then I have stripe add as framework:- ` .xcframework(path: .relativeToRoot("Stripe.xcframework"))`

**Comment by trevor-holliday-instacart** [comment]
I am seeing this issue as well with a carthage update command and no Tuist overhead.

**Comment by davidme-stripe** [comment]
Sorry for the trouble! Looks like we were unintentionally marking the *TestUtils schemes as shared after migrating to Tuist, this causes issues on Xcode 14.3, and our Carthage install tests were not configured to catch this issue.

We've landed a fix in `master` — it should work now if you set `requirement: .branch("master")` in tuist. We plan to cut a release including this fix on Monday.

**Comment by hassan-ioki** [comment]
@davidme-stripe maybe you need to included `StripePayments` added too as in your branch I still get error: 
`Module 'StripePayments' not found`. I have to explicitly add this framework to run my app successfully.

**Comment by stherold** [comment]
+1

**Comment by oleksandr-kozlovskyi** [comment]
+1

**Comment by davidme-stripe** [comment]
Including StripePayments is expected for version 23.x.x or later: We've split the SDK into separate components to reduce the size, and you may be able to remove the main Stripe framework to save a few MB. Here's a [summary of which frameworks to use, along with Carthage install instructions](https://stripe.com/docs/mobile/ios/sdk-23-migration).

This doesn't require changes when using Cocoapods or SPM (as they'll pick up the dependencies automatically), but Carthage and manual frameworks users will need to add dependent frameworks manually.

**Comment by hassan-ioki** [comment]
Just an update: This [release](https://github.com/stripe/stripe-ios/releases/tag/23.6.1) fixes it now for me. 🎉

**Comment by davidme-stripe** [comment]
Yes, this was fixed in [23.6.1](https://github.com/stripe/stripe-ios/releases/tag/23.6.1). Let me know if you have any other issues with Carthage!
