### ISSUE TITLE
[Feature] iOS Privacy Manifest Support

### ISSUE THREAD

**Issue by trevor-holliday-instacart** [stripe/stripe-ios#3409]
## Is your feature request related to a problem? Please describe.
Apple announced that all SDK providers are required to supply an privacy manifest for their usage. Will Stripe be creating a Privacy Manifest?

**Comment by GaeCuure** [comment]
any update on this?

**Comment by mammaiap** [comment]
when will the next release with "Privacy Manifest" support?.

**Comment by davidme-stripe** [comment]
We're [adding one here](https://github.com/stripe/stripe-ios/pull/3425), it'll be available in next week's update. Thanks for flagging!

**Comment by daveluong** [comment]
@davidme-stripe Thank you, do we have plan to support older version? We're still on `22.8.4`

**Comment by davidme-stripe** [comment]
We don't currently plan to, but I'll check if we can offer a hotfix. Can you share more on your use case for staying on 22.8.4? Do you need iOS 12 support?

**Comment by daveluong** [comment]
@davidme-stripe Yes we're supporting iOS 12 so must be on StripeSDK `22.8.4`

**Comment by davidme-stripe** [comment]
@daveluong We can spin up a tagged version for this, but Cocoapods' Specs repo doesn't have great support for backported versions. If you use Cocoapods, you would be able to use it by adding this to your Podfile:
`pod 'Stripe', :git => 'https://github.com/stripe/stripe-ios.git', :tag => '22.8.5'`

Would that work for your use case?

**Comment by daveluong** [comment]
```
 If you use Cocoapods, you would be able to use it by adding this to your Podfile:
pod 'Stripe', :git => 'https://github.com/stripe/stripe-ios.git', :tag => '22.8.5'
```
Thank you David, yes this is what we've been doing with StripeSDK pod

**Comment by porter-stripe** [comment]
Hi @daveluong we published a tag `22.8.4-privacy` which contains the privacy manifests. You can point to this tag similarly to what you have pointed out. Let us know if you encounter any issues.

```ruby
pod 'Stripe', :git => 'https://github.com/stripe/stripe-ios.git', :tag => '22.8.4-privacy'
```

**Comment by vijaytholpadi** [comment]
> @daveluong We can spin up a tagged version for this, but Cocoapods' Specs repo doesn't have great support for backported versions. If you use Cocoapods, you would be able to use it by adding this to your Podfile: `pod 'Stripe', :git => 'https://github.com/stripe/stripe-ios.git', :tag => '22.8.5'`
> 
> For SPM, you'll be able to point to the `22.8.5` tag.
> 
> Would that work for your use case?

@davidme-stripe Hi! I did not manage to find `22.8.5` tag [here](https://github.com/stripe/stripe-ios/tags). Can I confirm if it has been published? Wanted to consume this change via SPM.

Also I noticed a few compilation issues in the Package.swift and also a Missing `Privacy.xcprivacy` file in the `Stripe/` folder on the `22.8.4-privacy` tag, so wanted to confirm if the same is fixed on `22.8.5` as well.

**Comment by vijaytholpadi** [comment]
@davidme-stripe @porter-stripe Can I check on this please? Also happy to create a different issue if necessary. Thanks.

**Comment by porter-stripe** [comment]
@vijaytholpadi we did not publish a 22.8.5 tag, however we did publish a 22.8.4-privacy tag.

Additionally we just made some changes to get this working with Xcode 15 and updated the path of the privacy manifest in the Package.swift file.

Let me know if you encounter any more issues.

https://github.com/stripe/stripe-ios/releases/tag/22.8.4-privacy

**Comment by vijaytholpadi** [comment]
@porter-stripe I just downloaded the 22.8.4-privacy tag and notice that the compilation issues are still there in `Package.swift`.

![Screenshot 2024-06-28 at 8 03 10 AM](https://github.com/stripe/stripe-ios/assets/1171868/ab2b9db9-79d2-470e-9314-6d49923580b6)

The entries in the resources field seem to be missing a comma at the end.

Could you help release a fixed version for SPM please?

**Comment by porter-stripe** [comment]
@vijaytholpadi apologies, I fixed the compilation errors in the Xcode project not Package.swift, it should be fixed now. If you continue to encounter issues consider installing with Cocoapods or upgrading to the latest version for the best support as we can't guarantee support for this special version going forward. 

If you need additional support please open a new issue for best visibility. 
Thanks!
